services:
  - type: web
    name: winamax-bot
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: export PATH="${PATH}:/opt/render/project/.render/chrome/opt/google/chrome:/opt/render/project/.render/chromedriver" && python main.py
    autoDeploy: true
